### PR TITLE
apache thrift config file

### PR DESCRIPTION
**Pull request by leilani-reich**
Hello Carlos,
I've created a thrift.yml file for the Apache Thrift project, similar to other conf files like "helix.yml".

Thank you,
Leilani

### CODE REVIEW

**Review by carlosparadis — CHANGES_REQUESTED** [review]
Hi Leilani,

The config looks fine. In regards to NEWS.md, you should move the item to Documentation Fixes. I'd reserve New Features to your upcoming task with Bugzilla or dv8. 

Thanks!

**Review by carlosparadis — CHANGES_REQUESTED** [review]
The new contributor commit is modifying the Roxygen note version, so you may want to revert that. However, i'd save this new contributor commit to a code contribution versus docs, since this is very minimal.

**Comment by carlosparadis** [comment]
To avoid making another pull request, try to edit your fork's last 2 commits to reflect these changes, and it will automatically reflect here. If not sure how, CONTRIBUTIONS.md should have some resources towards the last section. Otherwise, your pull request looks great and follows perfectly the CONTRIBUTION.md!

**Comment by leilani-reich** [comment]
Hi Carlos, I edited my commits. I basically used git reset to remove commits and make changes. Does this work? Thank you. 

Also, I was learning about git commands via the learning resources on CONTRIBUTING.md and just wanted to let you know the last three links, "Create a Pull Request", "Stay in Sync with Code Repository", and "Commit Squash and Relabel" don't seem to link to a specific video; it just takes me to the Udacity "My Learning" page.

**Comment by carlosparadis** [comment]
This looks great! Thank you :)

**Pull request merged**
